# Generated by Django 4.1.3 on 2022-11-27 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_primenumber_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primenumber',
            name='prime_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='primenumber',
            name='range',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='primenumber',
            name='time_elapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
