# Generated by Django 4.1.3 on 2022-11-27 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_primenumber_prime_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primenumber',
            name='prime_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=100),
        ),
        migrations.AlterField(
            model_name='primenumber',
            name='range',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=100),
        ),
    ]
